name: deploy

on:
    push:
        branches: "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout the repository
                uses: actions/checkout@v4.1.1
            
            -   name: install nodejs
                uses: actions/setup-node@v4.0.0
                with:
                    node-version: 18
            
            -   name: install dependencies
                run: npm install
            
            -   name: build the project
                run: npm run build
            
            -   name: build the project
                run: npm run deploy
